version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to the Docker Hub...
      - docker login -u haridevelops -p harisudhan2004
      - echo Successfully logged in to the Docker Hub...
  build:
    commands:    
      - echo Build started on `date`
      - docker build --rm -f "Docketfile" -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed  on `date`
      - echo pushing the Docker image to Docker Hub...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG