version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to the Docker Hub...
      - docker login -u haridevelops -p harisudhan2004
      - echo Successfully logged in to the Docker Hub...
  build:
    commands:    
      - echo Build started...
      - docker build --rm -f "Dockerfile" -t haridevelops/aws-code-pipeline-testing:v2 .
      - docker tag haridevelops/aws-code-pipeline-testing:v2 haridevelops/aws-code-pipeline-testing:v2
      - docker images
  post_build:
    commands:
      - echo Build completed...
      - echo pushing the Docker image to Docker Hub...
      - docker push haridevelops/aws-code-pipeline-testing:v2